version: '3'

services:
  oracle-db:
    image: oracle/database:18.4.0-xe
    ports:
      - "1521:1521"
      - "8085:8080"
      - "5500:5500"
    shm_size: 1g
    volumes:
      - ./data:/u01/app/oracle/oradata
    environment:
      - ORACLE_PWD=1234
    restart: unless-stopped